--PROJECT TITLE: Museum Collection Insights: Exploring Artworks and Artist Data with SQL.

-- CREATE THE DATABASE:
CREATE DATABASE MOMA_ARTWORKS_COLLECTIONS;

--USE THE DATABASE :
USE MOMA_ARTWORKS_COLLECTIONS;

-- IMPORT THE DATA IN SQL:

SELECT * FROM ARTISTS

SELECT * FROM ARTWORKS

-- CLEANING THE DATA OF THE BOTH TABLES:

--FIRST ARTISTS TABLE:

UPDATE ARTISTS
SET GENDER=
CASE
    WHEN GENDER IN ('M','MALE','male') THEN 'Male'
	WHEN GENDER IN ('F','FEMALE','female') THEN 'Female'
	ELSE 'Unknown'
END

UPDATE ARTISTS
SET NATIONALITY = 'Unknown'
WHERE NATIONALITY IS NULL OR LTRIM(RTRIM(NATIONALITY))=''

UPDATE ARTISTS
SET DISPLAYNAME= 'Unknown'
WHERE DISPLAYNAME IS NULL OR LTRIM(RTRIM(DISPLAYNAME))=''

UPDATE ARTISTS
SET ARTISTBIO= 'Uknown'
WHERE ARTISTBIO IS NULL

UPDATE ARTISTS
SET BEGINDATE = 'Unknown'
WHERE CAST(BEGINDATE AS int) =0

ALTER TABLE ARTISTS
ALTER COLUMN BEGINDATE NVARCHAR(255)

UPDATE ARTISTS
SET ENDDATE = 'Unknown'
WHERE ENDDATE= 0

--SECONDLY ARTWORKS TABLE:

UPDATE ARTWORKS
SET TITLE = 'Unknown'
WHERE TITLE IS NULL OR LTRIM(RTRIM(TITLE)) = ''

UPDATE ARTWORKS 
SET DATE = 'Unknown'
WHERE DATE IS NULL OR LTRIM(RTRIM(DATE))='()'

UPDATE ARTWORKS
SET MEDIUM= 'Unknown'
WHERE MEDIUM IS NULL OR LTRIM(RTRIM(MEDIUM))=''

UPDATE ARTWORKS
SET DIMENSIONS = 'Unknown'
WHERE DIMENSIONS IS NULL OR LTRIM(RTRIM(DIMENSIONS))= ''


UPDATE ARTWORKS
SET HEIGHT_CM = CAST(HEIGHT_CM AS FLOAT),
    WIDTH_CM = CAST(WIDTH_CM AS FLOAT)

UPDATE ARTWORKS
SET DATEACQUIRED = NULL
WHERE CAST(DATEACQUIRED AS DATE) IS NULL


UPDATE ARTWORKS 
SET GENDER=
CASE 
    WHEN GENDER IN ('M','(male)','male') THEN 'Male' 
	WHEN GENDER IN ('F','(female)','female') THEN 'Female'
	WHEN GENDER IS NULL THEN 'Unknown'
    ELSE 'Unknown'
END

ALTER TABLE ARTWORKS 
ADD NEWDATE INT

UPDATE ARTWORKS
SET NEWDATE =CAST(SUBSTRING(DATE, PATINDEX('%[1-2][0-9][0-9][0-9]%',DATE),4) AS INT)
WHERE PATINDEX('%[1-2][0-9][0-9][0-9]%',DATE) >0

-- DATA CLEANING IS DONE.
-- NOW WE DO THE ANALYSIS QUESTION:

--Q1) How modern are the artworks at the Museum?

SELECT MIN(NEWDATE) AS 'EARLIEST_ARTWORKS',
       MAX(NEWDATE) AS 'MODERN_ARTWORKS',
	   COUNT(*) AS 'TOTAL_ARTWORKS',
	   SUM(CASE WHEN NEWDATE < 1900 THEN 1 ELSE 0 END) AS 'TOTAL_EARLIEST_ARTWORKS',
	   SUM(CASE WHEN NEWDATE >= 1900 THEN 1 ELSE 0 END) AS 'TOTAL_MODERN_ARTWORKS' 
FROM ARTWORKS
WHERE NEWDATE IS NOT NULL

--ANSWER
-- AS WE CAN SEE HERE THE TOTAL_MODERN_ARTWORKS IS MORE THEN THE TOTAL_EARLIEST_ARTWORKS SO THE ARTWORKS 
-- COLLECTIONS WAS STRONGLY FOCUSED ON THE MODERN CENTURY.

--Q2) Which artists are featured the most?

SELECT A.DISPLAYNAME , COUNT(*) AS 'ARTWORKS_COUNT' FROM ARTWORKS AW
JOIN ARTISTS A
ON A.CONSTITUENTID = AW.CONSTITUENTID
GROUP BY A.DISPLAYNAME
ORDER BY ARTWORKS_COUNT DESC

--ANSWER:
--AS WE CAN SEE HERE THE ARTIST 'Ludwig Mies van der Rohe' ARTWORKS COUNT WAS 15491, SO THIS ARTIST FREATURE THE MOST.

--Q3)Are there any trends in the dates of acquisition?

SELECT YEAR(DATEACQUIRED) AS 'ACQUIRED_YEAR', COUNT(*)  AS 'ARTWORKS_COUNT' FROM ARTWORKS
WHERE DateAcquired IS NOT NULL
GROUP BY YEAR(DATEACQUIRED)
ORDER BY ACQUIRED_YEAR

--ANSWER:
-- HERE THE TREND UP AT 1964-1968 AND DOWN AT 1929-1931.

--Q4) What types of artwork are most common?

SELECT CLASSIFICATION AS 'TYPE_OF_ARTWORKS', COUNT(*) AS 'ARTWORKS_COUNT' FROM ARTWORKS
GROUP BY CLASSIFICATION
ORDER BY ARTWORKS_COUNT DESC

--ANSWER:
-- THE PHOTOGRAPH TYPE OF ARTWORKS ARE THE MOST COMMON ARTWORKS.

--Q5) FROM MY END THE RECOMENDED ANALYSIS IS -> GENDER_WISE CONTRIBUTION BY ARTISTS?
-- THIS IS IMPORTANT BECAUSE IT HELPS TO UNDERSTAND DIVERSITY AND INCLUSION IN ART REPRESENTATION.

SELECT A.GENDER, COUNT(*) AS 'TOTAL_ARTWORKS' FROM ARTWORKS AW
JOIN ARTISTS A
ON A.ConstituentID= AW.ConstituentID
GROUP BY A.Gender



SELECT * FROM ARTWORKS
SELECT * FROM ARTISTS